### PR TITLE
Cleaned up project structure

### PR DESCRIPTION
**Pull request by arehmandev**
Currently its all in one main function - I decided to split out the functionality for you - feel free to test it - if happy merge and remember to change the import paths

### CODE REVIEW

**Comment by arehmandev** [comment]
Ended up adding in quite a bit of structure, feel free to take your time to review - let me know if there's any bugs

**Comment by usernameisalreadytaken0100** [comment]
Hi @arehmandev,
Whats the point of this Pull Request? I mean, sorry to say, but it's just a cleanup and adds nothing to the project. It should be a suggestion (in issues) to clean up the code to increase readability, not a PR. I wonder if @muhammadmuzzammil1998 (owner) would accept it.

**Comment by arehmandev** [comment]
@usernameisalreadytaken0100 - I agree, however I thought it would be nice to have community collaboration on how to best structure this code, this was more of a suggestion and a challenge to play around with last night.

**Comment by muhammadmuzzammil1998** [comment]
@usernameisalreadytaken0100, whats your problem?

@arehmandev Although this is great, it really does not, as @usernameisalreadytaken0100 said, add anything to the project. I would encourage you to keep the fork but I can't merge it. Sorry.

**Pull request closed without merging**
